version: "3.8"
services:
  postgres:
    image: 'postgres:latest'
    container_name: ff4j-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ff4jdb
      POSTGRES_USER: danny
      POSTGRES_PASSWORD: danny
    volumes:
      - ff4j-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s


networks:
  d2c-network:
    driver: bridge
volumes:
  ff4j-db: