server:
  servlet:
    context-path: /ff4j-server
  port: 8080

##Sprng settings
spring:
  application:
    name: ff4j-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ff4jdb
    username: danny
    password: danny
    name: ff4jdb
    driver-class-name: org.postgresql.Driver

##FF4J settings
ff4j:
  api:
    context-path: /api/v1/ff4j     # default '/api/ff4j'
    spring-doc:
      enabled: true                # default 'false'
  audit:
    enabled: false                  # default 'false'
  web-console:
    context-path: /ff4j-web        # default '/ff4j-web-console'
    enabled: true                  # default 'false'
springdoc:
  swagger-ui:
    #tags-sorter: "alpha"
    #operations-sorter: "alpha"
  #group-configs:
    #- group: "root"
      #pathsToMatch: "/**"
      #packagesToScan: "org.ff4j.spring.boot.starter.webmvc.sample.rest"